/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MakeRouteImport } from './routes/make'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as SellRouteImport } from './routes/sell'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MakeRoute = MakeRouteImport.update({
  id: '/make',
  path: '/make',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/make': typeof MakeRoute
  '/markets': typeof MarketsRoute
  '/playground': typeof PlaygroundRoute
  '/portfolio': typeof PortfolioRoute
  '/sell': typeof SellRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/make': typeof MakeRoute
  '/markets': typeof MarketsRoute
  '/playground': typeof PlaygroundRoute
  '/portfolio': typeof PortfolioRoute
  '/sell': typeof SellRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/make': typeof MakeRoute
  '/markets': typeof MarketsRoute
  '/playground': typeof PlaygroundRoute
  '/portfolio': typeof PortfolioRoute
  '/sell': typeof SellRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/make' | '/markets' | '/playground' | '/portfolio' | '/sell'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/make' | '/markets' | '/playground' | '/portfolio' | '/sell'
  id:
    | '__root__'
    | '/'
    | '/make'
    | '/markets'
    | '/playground'
    | '/portfolio'
    | '/sell'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MakeRoute: typeof MakeRoute
  MarketsRoute: typeof MarketsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PortfolioRoute: typeof PortfolioRoute
  SellRoute: typeof SellRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/make': {
      id: '/make'
      path: '/make'
      fullPath: '/make'
      preLoaderRoute: typeof MakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MakeRoute: MakeRoute,
  MarketsRoute: MarketsRoute,
  PlaygroundRoute: PlaygroundRoute,
  PortfolioRoute: PortfolioRoute,
  SellRoute: SellRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
