[package]
name = "zubidubi-aqua-liquidity-substreams"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hex = "0.4"
ethabi = "17.2"
num-bigint = "0.4"
prost = "0.13"
substreams = "0.7.6"
substreams-ethereum = "0.11.1"

[target.wasm32-unknown-unknown.dependencies]
getrandom = { version = "0.2", features = ["custom"] }
